<!DOCTYPE html>
<html lang="es">
	<head >
		<meta charset="utf-8">
		<meta name = "description" content="Web de fotos">
		<title>Fotos</title>
		<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
		<link rel="stylesheet" type="text/css" href="estilo.css" media="screen" title="Estilo principal">
        <link rel="stylesheet" type="text/css" href="estilo_imprimir.css" media="print">
        <link rel="alternate stylesheet" type="text/css" href="estilo_accesible.css" media="screen" title="Estilo accesible">
        <link rel="alternate stylesheet" type="text/css" href="estilo_clasico.css" media="screen" title="Estilo clásico">
	</head>