<form name="Login" action="control_acceso.php" method="post">
					<label for="usu"> Usuario:</label>
					<input type="text" id="usu" name="usu" required>

					<label for="contra"> Contraseña:</label>
					<input type="password" id="contra" name="contra" required>

			        <label for="recordar"> Recordarme en este equipo: </label>
			        <input type="checkbox" id="recordar" name="recordar">

					<input class="puntero_mano" type="submit" name="Enviar">
				</form>