<ul>
				<li><a href="index.php">Inicio</a></li>
				<li><a href="busqueda.php">B&uacute;squeda</a></li>
				<li><a href="menu_user_logeado.php">Menú de usuario</a></li>
			</ul>
			<form name="busqueda" class="buscador" action="res_busqueda.php" method="post">
				<input type="search" name="tit" placeholder="Título">
                <input class="puntero_mano" type="submit" name="Enviar">
			</form>